### ISSUE TITLE
Using call method on IOS Simulator throws an exception

### ISSUE THREAD

**Issue by clementdevosmc** [apizee/reactNativeApiRTC#2]
Hello !

I've been trying to implement your library in my application but i've got an issue with the iOS implementation. 

Android works fine but iOs throws an error on the call method, see as depicted below.
I've been able to reproduce this on your demo as well. 

![image](https://user-images.githubusercontent.com/32271083/31454908-4f126c9c-aeb7-11e7-9b60-58767206f48f.png)

Can you see what's wrong?

**Comment by FredLuart** [comment]
Hello,
Are you testing on a real device ? or with simulator ?
It seams to be a issue with the video stream

**Comment by clementdevosmc** [comment]
Hello Frédéric,

I'll try to run it on a real device to confirm this.

Cheers,

Clément

**Comment by minhduchua** [comment]
@clementdevosmc
I had this issue when using JS remote debugging.
Try turning off JS remote debugging and using the safari développer console instead.

**Comment by clementdevosmc** [comment]
OK i can confirm that it's working on a real device (iPhone 6) but not on the simulator, even without remote JS debugging... 
Do you think this is fixable or we're forced to code on a real device?

**Comment by minhduchua** [comment]
@clementdevosmc
Have you tired dismissing the error by clicking  the lower-left button?
Normally the simulator then runs on, which allows you to use simulator for development

**Comment by FredLuart** [comment]
Closing the issue : simulator can cause issues
