### ISSUE TITLE
How do I disable Audio?

### ISSUE THREAD

**Issue by spkprav** [apizee/reactNativeApiRTC#5]
Kindly let me know how do I disable the audio with this.

```
let callConf = {
   mediaTypeForOutgoingCall : 'VIDEOONLY',
   muted : 'AUDIOONLY'
};
const callId = this.webRTCClient.call(this.state.selected, {}, callConf);
```

I tried the above, but not working.

**Comment by spkprav** [comment]
@FredLuart Please help.

**Comment by francois-legoff** [comment]
Are you using latest version ? (https://cloud.apizee.com/apiRTC/apiRTC-latest.min.js)
With your configuration, the call transmitted has no audio, but on remote side when you accept call, you need to add parameter on method : acceptCall(callId, callConfiguration). More information :  https://apirtc.com/wp-content/themes/wikee/docs/apiRTC/module-ApiRTCWebRTCClient.html#acceptCall__anchor

**Comment by FredLuart** [comment]
Make sure to use the latest reactNative version of apiRTC : https://cloud.apizee.com/apiRTC/v3.18/apiRTC-React-latest.min.debug.js

**Comment by spkprav** [comment]
@francois-legoff @FredLuart 
Hi, Thanks for the reply, I will use this and let you know if it works.

**Comment by spkprav** [comment]
Didn't work, so I forked react-native-webrtc and disabled the permission.
