### ISSUE TITLE
This project is not working, is there any updated version?

### ISSUE THREAD

**Issue by spkprav** [apizee/reactNativeApiRTC#6]
Any help would be appreciated, I have been working on this project on and off for a year and now nothing works due to android deprecated a lot of things last year.

**Comment by FredLuart** [comment]
Hello,
Do you have some detailed information about your issue ? We have tested the project on an Android 8.0 device without any issues.

**Comment by seavan** [comment]
This project is very legacy. It's intended version of react-native-webrtc depends on react-native 0.40, which is outdated and literally impossible to publish to iOS or Android store (no x64 support for Android).

Please, update the react native client to work with the latest react-native-webrtc

**Comment by spkprav** [comment]
Closing this issue, as it is impossible to use webrtc because of a lot of issues. I had to remove the feature itself and use video-sharing instead.

**Comment by FredLuart** [comment]
Hello, for your information we will check this issue and provide an update

**Comment by FredLuart** [comment]
Closing this issue
